spring.config.import=aws-parameterstore:/sparta-aws/prod/
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
info.team-name=${TEAM_NAME}
management.info.env.enabled=true
spring.cloud.aws.s3.bucket=sparta-aws-choehyeongmin7-files

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true