spring.application.name=Sparta_AWS
spring.profiles.active=prod

server.port=8080

# AWS Region
spring.cloud.aws.region.static=ap-northeast-2

# ?? ??? ?? ??
spring.servlet.multipart.max-file-size=10MB

management.endpoints.web.exposure.include=health,info